### ISSUE TITLE
Encountering rigid misalignment

### ISSUE THREAD

**Issue by gerwang** [QianyiWu/get_mesh_py_API#1]
Hi,

When I applied the ACAP feature of one neutral face to the mean face, I find it misaligned with the original neutral face.

RT
![image](https://user-images.githubusercontent.com/25758401/65374602-589b9900-dcbe-11e9-9547-be9446e4f2fe.png)

When I applied the "identity feature" (i.e. `np.array([1, 0, 0, 1, 0, 1, 0, 0, 0])`) to a face, I also noticed the rigid transformation.

Is it just a feature of ACAP so I need to perform rigid alignment as post processing?

Thanks in advance.

**Comment by gerwang** [comment]
A short script to reproduce the behavior is
```python

    tmp = get_mesh.get_mesh(mean_face_path,
                            get_dr.get_dr(mean_face_path,
                                          'Tester_{}/Blendshape/shape_0.obj'.format(i)))
```

**Comment by QianyiWu** [comment]
Hi

It is the feature of DR (or ACAP if you used). You can perform the rigid alignment to solve the mismatch problem as it will not influence the overall shape computed by DR (ACAP). It is maybe an easier and better solution when visualization.

**Comment by gerwang** [comment]
Thanks, solved my problem.
